ci(latest): autoupdate checkout connector
commercetools/connect-payment-integration-template pull request #236
Opened 2024-06-10 18:42 UTC by ddeliziact

@leungkinghin-ct @prateek-ct I have no access to the repository setting and I would like to setup the following repository variables:

* CKO_CLIENT_ID
* CKO_CLIENT_SECRET
* CKO_CONNECTOR_KEY

2024-06-11 08:11 UTC, leungkinghin-ct requested changes
@ddeliziact Thank you for building autoupdate in pipeline for the mock connector. I also don't have right to set env-var for this repo
@prateek-ct @praveenkumarct 
Can you find env-var configuration page inside repo settings? Please help to set up following env-var for this repo
- CKO_CLIENT_ID
- CKO_CLIENT_SECRET
- CKO_CONNECTOR_KEY

2024-06-11 08:45 UTC, ddeliziact commented on .github/workflows/latest.yml
> +      CTP_REGION: ${{ secrets.CTP_REGION }}
I have removed that... the idea for such environment variables is to use the one for the checkout private connectors, if you plan also to have the ones for the official connectors, we can create another pipeline with additional environment variables. What do you think?

2024-06-11 12:56 UTC, leungkinghin-ct approved these changes

2024-06-13 11:26 UTC, praveenkumarct approved these changes

2024-06-13 11:26 UTC, merged